config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :messages

  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login, via: [:get, :post]
  match 'logout' => "user_sessions#destroy", :as => :logout, via: [:get, :post]
  get 'tags/:tag', to: 'posts#index', as: "tag"

  resources :users

   root 'posts#index'

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # specify configuration here, such as:
  # logout_on_timeout true
  # ...many more options in the documentation



end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :set_user_session, only: [:show, :edit, :update]
  before_filter :redirect, only: [:index, :show, :edit]
  # GET /user_sessions
  # GET /user_sessions.json
  def index
    @user_sessions = UserSession.all
  end

  # GET /user_sessions/1
  # GET /user_sessions/1.json
  def show
  end

  # GET /user_sessions/new
  def new
    @user_session = UserSession.new
  end

  # GET /user_sessions/1/edit
  def edit
  end

  # POST /user_sessions
  # POST /user_sessions.json
  def create
    @user_session = UserSession.new(user_session_params)

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to @user_session, notice: 'User session was successfully created.' }
        format.json { render :show, status: :created, location: @user_session }
      else
        format.html { render :new }
        format.json { render json: @user_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_sessions/1
  # PATCH/PUT /user_sessions/1.json
  def update
    respond_to do |format|
      if @user_session.update(user_session_params)
        format.html { redirect_to @user_session, notice: 'User session was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_session }
      else
        format.html { render :edit }
        format.json { render json: @user_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.json
  def destroy
    @user_session = UserSession.find

    if @user_session
      @user_session.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Goodbye!' }
        format.json { head :no_content }
      end
    else
      redirect_to login_url
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_session
      @user_session = UserSession.find(params[:id])
    end

  def redirect
    redirect_to root_path
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_session_params
      params.require(:user_session).permit(:username, :password)
    end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>
      <ul>
      <% @user_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing User Session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Sessions</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_sessions.each do |user_session| %>
      <tr>
        <td><%= user_session.username %></td>
        <td><%= user_session.password %></td>
        <td><%= link_to 'Show', user_session %></td>
        <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
        <td><%= link_to 'Destroy', user_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<h1>Login To Get Access</h1>

<%= render 'form' %>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user_session.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user_session.password %>
</p>

<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>